import {
  AdminUserIcon,
  ApplyForJobIcon,
  BlogsIcon,
  BranchLocatorIcon,
  BusinessLoan,
  CityIcon,
  CommercialSolarFinance,
  CountryIcon,
  CRMIcon,
  DealerFinance,
  Disclosure,
  HomeLoanImage,
  Job,
  LoanAgainstProperty,
  LookUpCategoryIcon,
  LookUpValueIcon,
  MachineryEquipmentLoanImage,
  MachineryLoan,
  PurchaseInvoiceDiscounting,
  ResidentialSolarFinance,
  RevenueBasedFunding,
  SaleInvoiceDiscounting,
  StateIcon,
  VendorFinance,
  WorkingCapitalLoanImage,
  YoutubeIcon,
} from "@/assets";
import { KeyboardEventHandler } from "react";

export const API_V1 = "/api/v1";

export const LOOKUP_VALUES = {
  JOB_TYPE: "JOB_TYPE",
  DISCLOSURE: "DISCLOSURE",
  LANGUAGE: "LANGUAGE",
  TESTIMONIAL: "TESTIMONIAL",
  PROMOTIONAL: "PROMOTIONAL",
  PRODUCT_EXPLAINERS: "PRODUCT_EXPLAINERS",
  BLOGS_CATEGORY: "BLOGS_CATEGORY",
};

export const ROUTES = {
  home: "/",

  // Admin routes
  admin: {
    signIn: "/admin/sign-in",
    adminUser: "/admin/admin-user",
    branchLocator: "/admin/branch-locator",
    blogs: "/admin/blogs",
    job: "/admin/job",
    disclosure: "/admin/disclosure",
    city: "/admin/city",
    country: "/admin/country",
    state: "/admin/state",
    youtube: "/admin/youtube",
    applyForJob: "/admin/apply-for-job",
    applyForLoan: "/admin/crm/apply-for-loan",
    contactUs: "/admin/crm/contact-us",
    requestCall: "/admin/crm/request-a-call",
    lookupCategory: "/admin/lookup-category",
    lookupValue: "/admin/lookup-value",
    nach: "/admin/nach",
  },

  // Client routes
  client: {
    aboutus: "/about-us",
    blogs: "/blogs",
    branchLocator: "/branch-locator",
    careers: "/careers",
    contactUs: "/contact-us",
    disclosures: "/disclosures",
    possibleHai: "/possible-hai",
    registerAsChannelPartner: "/register-as-channel-partner",
    checkCreditScore: "/check-credit-score",
    termsAndConditions: "/terms-and-conditions",
    disclaimer: "/disclaimer",
    privacyPolicy: "/privacy-policy",
    search: "/search",
    partnerships: "/partner-ships",
  },

  // Products routes
  product: {
    businessLoan: "/business-loan",
    commercialSolarLoan: "/commercial-solar-loan",
    homeLoan: "/loans-backed-by-property/home-loan",
    loanAgainstProperty: "/loan-against-property",
    microlap: "/loans-backed-by-property/micro-lap",
    machineryLoan: "/machinery-loan",
    residentialSolarLoan: "/residential-solar-loan",
    scfPurchaseInvoice: "/supply-chain-finance/purchase-invoice",
    scfSalesInvoiceDiscounting: "/supply-chain-finance/sales-invoice-discounting",
    scfVendorFinance: "/supply-chain-finance/vendor-finance",
    scfDealerFinance: "/supply-chain-finance/dealer-finance",
    workingCapitalLoan: "/working-capital-loan",
    revenuebasedfinance: "/revenue-based-finance",
  },

  adminAllowed: ["/admin/sign-in"],
};

export enum USER_TYPES {
  ADMIN = "admin",
}

export enum EMAILS {
  INFO = "ops.nbfc@ratnaafin.com",
  CON_INFO = "info@ratnaafin.com",
  GRIEVANCE = "grievance@ratnaafin.com",
  CAREERS = "careers@ratnaafin.com",
}
export enum TELS {
  INFO = "18003098013",
  CON_INFO = "18003098010",
  GRIEVANCE = "9512011220",
  INFO_FOOTER = "18003098013",
}
export enum PUBLIC_IMAGE {
  ratnaafinLogo = "/images/ratnaafin_logo.webp",
  rLogo = "/images/R_logo.webp",
}

export enum URLS {
  FINSURE = "https://www.ratnaafinsure.com/",
  PARTNER_PORTAL = "https://los.ratnaafin.com/partner-portal/signup",
  POSP = "https://app.ratnaafinsure.com/POSSignup",
  CUSTOMERS = "https://customer.ratnaafin.com/",

  RBI_SACHET = "https://sachet.rbi.org.in/",
  RBI_CMS = "https://cms.rbi.org.in/cms/indexpage.html",

  FACEBOOK = "https://www.facebook.com/theratnaafin/",
  INSTAGRAM = "https://www.instagram.com/ratnaafin/",
  YOUTUBE = "https://www.youtube.com/@Ratnaafin",
  LINKEDIN = "https://in.linkedin.com/company/ratnaafin",

  LINKEDIN_NILESH = "https://www.linkedin.com/in/nilesh-sanghvi-b1437721",
  LINKEDIN_MALAV = "https://www.linkedin.com/in/malav-desai-9547272a",
  LINKEDIN_NISHAD = "https://www.linkedin.com/in/nishad-shah-68844b14",
  LINKEDIN_DHAVAL = "https://www.linkedin.com/in/dhaval-patel-56446826b",
  LINKEDIN_OM_PRAKASH_MISHRA = "https://www.linkedin.com/in/om-prakash-mishra-6526b3165/",
  LINKEDIN_DC_JAIN = "https://www.linkedin.com/in/d-c-jain-99895398/",

  MAPS_THE_RIDGE = "https://maps.app.goo.gl/XT3zn6EDjQAzqRS7A",
  MAPS_BHIKAJI = "https://maps.app.goo.gl/eH4da1mDq47B7ihn9",

  GRAYQUEST = "https://grayquest.com",
  FINSALL = "https://www.finsall.com",
  THEEMICLUB = "https://theemiclub.com",
  JODO = "https://www.jodo.in",
}

export const SearchObj = {
  search: "",
  searchValue: "",
};

export const VIDEO_URL = `${API_V1}/video-player?fileName=`;

export const handleKeyDown: KeyboardEventHandler<HTMLInputElement> = (e) => {
  const { type } = e.target as HTMLInputElement;
  const numberDisallowedKeys = ["ArrowUp", "ArrowDown", "-", ".", "+", "e", "E"];

  if (type === "number" && numberDisallowedKeys.includes(e.key)) {
    e.preventDefault();
    return;
  }
};

export function convertMediaUrl(path: string) {
  return `${process.env.NEXT_PUBLIC_FRONTEND_URL}${API_V1}${path || ""}`;
}

export async function ipAddress() {
  try {
    const res = await fetch("https://api.ipify.org?format=json");
    const data = await res.json();

    return data.ip;
  } catch (error) {
    console.error("Error fetching IP:", error);
  }
}

export const convertVideoUrl = (docPath: string) => {
  return `${process.env.NEXT_PUBLIC_FRONTEND_URL}${VIDEO_URL}${docPath}`;
};

export const generateValueCode = (value: string) => {
  return value
    .toUpperCase()
    .replace(/[^a-zA-Z\s]/g, "")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_");
};

export const adminSideBarData = [
  {
    id: 0,
    label: "Admin",
    path: ROUTES.admin.adminUser,
    icon: AdminUserIcon,
  },
  {
    id: 1,
    label: "Blogs",
    path: ROUTES.admin.blogs,
    icon: BlogsIcon,
  },
  {
    id: 2,
    label: "Branch Locator",
    path: ROUTES.admin.branchLocator,
    icon: BranchLocatorIcon,
  },

  {
    id: 3,
    label: "City",
    path: ROUTES.admin.city,
    icon: CityIcon,
  },
  {
    id: 4,
    label: "CRM",
    icon: CRMIcon,
    dropdown: [
      {
        id: 1,
        label: "Apply For Loan",
        path: ROUTES.admin.applyForLoan,
      },
      {
        id: 2,
        label: "Contact Us",
        path: ROUTES.admin.contactUs,
      },
      {
        id: 3,
        label: "Request A Call",
        path: ROUTES.admin.requestCall,
      },
    ],
  },
  {
    id: 5,
    label: "Country",
    path: ROUTES.admin.country,
    icon: CountryIcon,
  },
  {
    id: 6,
    label: "Disclosure",
    path: ROUTES.admin.disclosure,
    icon: Disclosure,
  },
  {
    id: 7,
    label: "Jobs",
    path: ROUTES.admin.job,
    icon: Job,
  },
  {
    id: 8,
    label: "Jobs Applied",
    path: ROUTES.admin.applyForJob,
    icon: ApplyForJobIcon,
  },
  {
    id: 9,
    label: "Lookup Category",
    path: ROUTES.admin.lookupCategory,
    icon: LookUpCategoryIcon,
  },
  {
    id: 10,
    label: "Lookup Value",
    path: ROUTES.admin.lookupValue,
    icon: LookUpValueIcon,
  },
  {
    id: 11,
    label: "Nach",
    path: ROUTES.admin.nach,
    icon: LookUpValueIcon,
  },
  {
    id: 12,
    label: "State",
    path: ROUTES.admin.state,
    icon: StateIcon,
  },
  {
    id: 13,
    label: "Youtube",
    path: ROUTES.admin.youtube,
    icon: YoutubeIcon,
  },
];

export const SEARCHPAGE = [
  {
    name: "Home",
    keywords: [
      "Home",
      "msme",
      "business",
      "loan",
      "finance",
      "nbfc",
      "rbi",
      "capital",
      "working capital",
      "machinery loan",
      "sme",
      "micro finance",
      "credit",
      "funding",
      "enterprise",
      "registered",
      "solution",
      "growth",
    ],
    href: ROUTES.home,
  },
  {
    name: "About Us",
    keywords: [
      "Ratnaafin",
      "NBFC",
      "Non-Banking Financial Company",
      "MSME",
      "financial solutions",
      "business loans",
      "Ratnamani Group",
      "small business growth",
      "entrepreneur finance",
      "corporate finance India",
      "micro enterprises",
      "SME empowerment",
      "business funding",
      "financial support",
      "India NBFC",
      "business development finance",
      "financial services",
      "Ratnaafin About Us",
      "NBFC India",
      "trusted NBFC",
    ],
    href: ROUTES.client.aboutus,
  },
  {
    name: "Blogs",
    keywords: [
      "blogs",
      "insights",
      "updates",
      "ratnaafin",
      "msme finance",
      "business growth",
      "nbfc",
      "loan tips",
      "financial solutions",
      "credit score",
      "credit report",
      "credit history",
      "credit rating",
      "improve credit score",
      "cibil",
      "equifax",
      "experian",
      "high mark",
      "working capital",
      "working capital loan",
      "drawing power",
      "loan eligibility",
      "business finance",
      "financial planning",
      "small business",
      "micro enterprise",
      "medium enterprise",
      "sme",
      "solar finance",
      "rbi",
      "credit card",
      "loan repayment",
      "interest rate",
      "loan approval",
      "credit utilization",
      "loan against property",
      "online loan",
      "credit mix",
      "credit bureaus",
      "credit utilization ratio",
      "udhyam registration",
      "udyam portal",
      "make in india",
    ],
    href: ROUTES.client.blogs,
  },
  {
    name: "Careers",
    keywords: [
      "Ratnaafin",
      "careers",
      "job openings",
      "NBFC",
      "India NBFC",
      "fastest-growing NBFC",
      "career opportunities",
      "join Ratnaafin",
      "financial services",
      "empower businesses",
      "dynamic team",
      "job listings",
      "Ratnaafin careers",
      "work at Ratnaafin",
      "NBFC job openings",
      "finance career India",
    ],
    href: ROUTES.client.careers,
  },
  {
    name: "Contact Us",
    keywords: [
      "Ratnaafin",
      "Contact Ratnaafin",
      "business loans",
      "MSME finance",
      "financial solutions",
      "get in touch Ratnaafin",
      "Ratnaafin contact number",
      "email Ratnaafin",
      "Ratnaafin branch",
      "apply for loan",
      "contact financial advisor",
      "loan support",
      "customer support",
      "loan assistance",
      "financial services India",
      "contact us form",
      "reach Ratnaafin",
      "loan queries",
      "business finance support",
      "financial consultancy",
    ],
    href: ROUTES.client.contactUs,
  },
  {
    name: "Possible Hai",
    keywords: [
      "Ratnaafin",
      "Possible Hai",
      "Business loans",
      "Solar loans",
      "Personal finance",
      "Loan eligibility",
      "Apply for loan",
      "Financial empowerment",
      "Online loan application",
      "Loan services India",
      "Customer financial journey",
      "Ratnaafin loan offers",
      "25,000+ customers",
      "Loan for business growth",
      "Solar financing solutions",
    ],
    href: ROUTES.client.possibleHai,
  },
  {
    name: "Register as Channel Partner",
    keywords: [
      "Ratnaafin",
      "Channel Partner",
      "NBFC",
      "Register as Channel Partner",
      "Business Loan Partner",
      "Partner with Ratnaafin",
      "MSME growth",
      "Business loan solutions",
      "Financial services India",
      "NBFC partnership",
      "Loan agent registration",
      "Partner registration form",
      "Earn with loans",
      "Fintech partner India",
      "Ratnaafin registration",
    ],
    href: ROUTES.client.registerAsChannelPartner,
  },

  {
    name: "Disclosures",
    keywords: [
      "Ratnaafin",
      "Disclosures",
      "Regulatory Information",
      "NBFC",
      "Compliance",
      "Compliance policies",
      "Transparent practices",
      "Official disclosures",
      "Financial transparency",
      "Non-Banking Financial Company",
      "Disclosure page",
      "Regulatory compliance",
      "NBFC compliance",
      "Ratnaafin disclosures",
      "Financial regulations",
      "Financials (Year wise)",
      "Annual Report",
      "Annual Return",
      "Board of Directors",
      "Policies and Codes",
      "Salient Features of Ombudsman Scheme",
      "Fair Practice Code",
      "Other Disclosures",
      "Public Disclosures of Liquidity Risk Management",
      "Partnership & Alliance",
      "Terms & Conditions of Appointment of Independent Director",
      "General Meetings",
      "Grievance details of LSP/DSA",
      "Corporate Social Responsibility",
      "SARFAESI",
      "Active Collection List",
      "NPA Guidelines",
      "Ratings",
      "Auction Notice",
    ],
    href: ROUTES.client.disclosures,
  },
  {
    name: "Terms & Conditions",
    keywords: [
      "Terms and Conditions",
      "Ratnaafin NBFC",
      "user agreement",
      "website policy",
      "privacy policy",
      "disclaimer",
      "cookies usage",
      "third party disclaimer",
      "information accuracy",
      "liability limitation",
      "user responsibilities",
      "intellectual property",
      "unauthorized use",
      "external links disclaimer",
      "governing law",
      "jurisdiction Ahmedabad",
      "RCPL services",
      "legal terms",
      "financial services",
      "Indian law",
    ],
    href: ROUTES.client.termsAndConditions,
  },
  {
    name: "Disclaimer",
    keywords: [
      "Ratnaafin",
      "NBFC",
      "Ratnaafin Capital",
      "financial disclaimer",
      "legal disclaimer",
      "terms and conditions",
      "information accuracy",
      "website liability",
      "forward-looking statements",
      "third-party websites",
      "copyright",
      "trademarks",
      "India jurisdiction",
      "Ahmedabad court",
      "financial services",
      "disclaimer",
      "legal notice",
      "user responsibility",
      "regulatory compliance",
      "investment disclaimer",
      "risk factors",
      "data usage",
      "content copyright",
      "financial advice warning",
      "merchantability",
      "non-infringement",
      "user agreement",
      "website terms",
    ],
    href: ROUTES.client.disclaimer,
  },
  {
    name: "Branch Locator",
    keywords: [
      "branch locator",
      "find branch",
      "nearest branch",
      "Ratnaafin branches",
      "Ratnaafin locations",
      "city branches",
      "NBFC locations",
      "contact branch",
      "branch map",
      "branch address",
      "branch contact",
      "Gujarat branches",
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Mumbai",
      "Delhi",
      "Karnataka",
      "Bangalore",
      "financial help",
      "visit branch",
      "India branches",
      "regional offices",
      "branch phone number",
      "branch email",
      "map directions",
      "corporate office",
      "branch list",
      "growth journey",
      "personal assistance",
    ],
    href: ROUTES.client.branchLocator,
  },
  {
    name: "Partnerships",
    keywords: [
      "Partnerships",
      "strategic partnerships",
      "embedded credit",
      "credit access",
      "loan partners",
      "GrayQuest",
      "The EMI Club",
      "education finance",
      "mobile phone loan",
      "plug-in credit",
      "seamless credit solutions",
      "customer acquisition",
      "recovery services",
      "customer service",
      "financial institutions",
      "school loans",
      "EMI solutions",
      "fintech partner",
      "RCPL",
      "Ratnaafin",
      "grievance redressal",
      "privacy policy",
      "partnership form",
    ],
    href: ROUTES.client.partnerships,
  },
  {
    name: "Business Loan",
    keywords: [
      "business loan",
      "apply business loan",
      "ratnaafin",
      "loan up to 50 lakh",
      "1.2% interest rate",
      "quick approval",
      "minimum documentation",
      "2025",
      "loan online",
      "loan application",
      "loan interest",
      "loan documents",
      "business financing",
      "loan for MSME",
      "small business loan",
      "startup loan",
      "instant loan",
      "loan eligibility",
      "business loan page",
      "public products",
    ],
    href: ROUTES.product.businessLoan,
  },
  {
    name: "Loan Against Property",
    keywords: [
      "loan against property",
      "property loan",
      "ratnaafin",
      "loan at low interest",
      "apply loan 2025",
      "loan with easy EMI",
      "minimal documentation loan",
      "loan using house",
      "high value loan",
      "mortgage loan",
      "lap",
      "secured loan",
      "loan for business expansion",
      "low interest loan",
      "loan application",
      "loan eligibility",
      "loan approval",
      "loan documents",
      "quick loan",
      "loan for property owners",
    ],
    href: ROUTES.product.loanAgainstProperty,
  },
  {
    name: "Micro Loan Against Property",
    keywords: [
      // Primary Keywords
      "Micro Loan Against Property",
      "MSME Loans in India",
      "Collateral Based Loans India",
      "MILAP Loan Ratnaafin",
      "Small Business Loan Rural India",
      "Fast MSME Financing India",
      "Loan Against Property for Small Business",

      // Supporting / Long-Tail Keywords
      "Micro LAP loan for MSME",
      "MILAP micro loans for business",
      "Ratnaafin MSME loan",
      "Secure loan for rural entrepreneurs",
      "Affordable MSME loans India",
      "Quick loan against property for startups",

      // URL / Contextual Path-based Keywords
      "loans-backed-by-property",
      "micro-lap",
      "public business loans India",
    ],
    href: ROUTES.product.microlap,
  },
  {
    name: "Machinery Loan",
    keywords: [
      // Primary Keywords
      "Machinery Loan",
      "Equipment Finance",
      "Machinery Loan Online",
      "Loan for Equipment Purchase",
      "Apply for Machinery Loan 2025",
      "Ratnaafin Machinery Loan",
      "Instant Equipment Loan India",
      "Loan for Industrial Equipment",
      "Equipment Loan for Business",

      // Supporting Keywords
      "Loan for buying machinery",
      "Business machinery financing",
      "Loan for construction equipment",
      "Loan for factory machines",
      "Heavy machinery loan approval",
      "Loan with minimal documentation",
      "Loan for equipment upgrade",
      "Loan up to ₹5 Crore for machinery",

      // URL & Context-based
      "machinery-loan",
      "equipment-finance-online",
      "ratnaafin-equipment-loan",
    ],
    href: ROUTES.product.machineryLoan,
  },
  {
    name: "Residential Solar Finance",
    keywords: [
      "residential solar loan",
      "solar loan in India",
      "solar financing India",
      "rooftop solar loan",
      "Ratnaafin solar loan",
      "easy solar financing",
      "low interest solar loan",
      "solar loan EMI options",
      "quick approval solar loan",
      "clean energy loan",
    ],
    href: ROUTES.product.residentialSolarLoan,
  },
  {
    name: "Commercial/Industrial Solar Finance",
    keywords: [
      "commercial solar loan",
      "industrial solar loan",
      "solar financing",
      "India solar loan",
      "clean energy loan",
      "Ratnaafin",
      "low interest solar loan",
      "quick approval loan",
      "flexible EMI solar",
      "solar loan India",
      "commercial solar system",
      "industrial energy loan",
      "solar power financing",
      "business solar panel loan",
      "easy solar financing",
      "renewable energy loan",
    ],
    href: ROUTES.product.commercialSolarLoan,
  },
  {
    name: "Home Loan",
    keywords: [
      "Home Loan",
      "Apply Home Loan Online",
      "Low Interest Home Loan",
      "2025 Home Loan",
      "Home Loan up to 75 Lakhs",
      "Ratnaafin Home Loan",
      "Fast Home Loan Processing",
      "Minimal Documentation Home Loan",
      "Flexible Home Loan Repayment",
      "Housing Finance",
      "Property Loan",
      "Loan Against Property",
      "Affordable Housing Loan",
      "Best Home Loan Interest Rates",
      "Online Loan Application",
    ],
    href: ROUTES.product.homeLoan,
  },
  {
    name: "Vendor Finance",
    keywords: [
      "vendor finance",
      "supply chain finance",
      "MSME loans",
      "Ratnaafin",
      "early invoice payments",
      "collateral free loans",
      "invoice financing",
      "cash flow solutions",
      "finance for vendors",
      "business finance",
      "vendor funding",
      "grow your MSME",
      "invoice discounting",
      "vendor finance interest rate",
      "1.20% loan rate",
      "vendor credit line",
      "financial support MSMEs",
      "short term business loan",
      "vendor cash advance",
      "working capital for vendors",
    ],
    href: ROUTES.product.scfVendorFinance,
  },
  {
    name: "Dealer Finance",
    keywords: [
      "dealer finance",
      "MSMEs finance",
      "Ratnaafin",
      "dealer loan",
      "anchor payments",
      "inventory financing",
      "flexible repayment",
      "dealer funding",
      "upfront payment",
      "supply chain finance",
      "ratnaafin capital",
      "monthly rate 1.10%",
      "dealer working capital",
      "financial solutions for dealers",
    ],
    href: ROUTES.product.scfDealerFinance,
  },
  {
    name: "Sale Invoice Discounting",
    keywords: [
      "Sale Invoice Discounting",
      "Ratnaafin Invoice Discounting",
      "Cash Flow for MSMEs",
      "Invoice Finance",
      "Instant funds 24-48 hours",
      "Collateral-free working capital",
      "MSME funding",
      "Sales invoice loan",
      "Invoice discounting at 1.2%",
      "Working capital Ratnaafin",
      "Ratnaafin MSME support",
      "B2B invoice finance",
      "Boost cash flow MSME",
      "Accounts receivable finance",
      "Fast invoice loan",
    ],
    href: ROUTES.product.scfSalesInvoiceDiscounting,
  },
  {
    name: "Purchase Invoice Discounting",
    keywords: [
      "purchase invoice financing",
      "purchase invoice loan",
      "purchase invoice funding",
      "collateral-free financing",
      "invoice discounting",
      "invoice finance",
      "ratnaafin invoice finance",
      "quick invoice loan disbursal",
      "flexible invoice financing",
      "supplier relationship finance",
      "cash flow loan",
      "business finance solution",
      "supply chain finance",
      "purchase invoice",
      "growth possible hai",
      "ratnaafin loan",
      "invoice loan with low interest",
      "1.2% invoice financing",
      "fast invoice funding",
      "working capital financing",
    ],
    href: ROUTES.product.scfPurchaseInvoice,
  },
  {
    name: "Working Capital Loan",
    keywords: [
      "MSME loan",
      "RBI registered NBFC",
      "Working Capital Loan",
      "SME financing solutions",
      "Machinery Loans",
      "business capital",
      "loan for MSME",
      "working capital funding",
      "NBFC loan provider",
      "business growth loan",
      "apply MSME loan online",
      "unsecured business loan",
      "fast business loan approval",
    ],
    href: ROUTES.product.workingCapitalLoan,
  },
  {
    name: "Revenue Based Funding",
    keywords: [
      "MSME loan",
      "RBI registered NBFC",
      "Working Capital Loan",
      "SME financing",
      "Machinery Loan",
      "business loan",
      "capital for business",
      "NBFC loan",
      "revenue based finance",
      "small business funding",
      "SME funding solutions",
      "business growth capital",
      "MSME financing solutions",
      "working capital for SMEs",
    ],
    href: ROUTES.product.revenuebasedfinance,
  },
  {
    name: "Insurance Services",
    keywords: [
      "insurance",
      "ratnaafin",
      "insurance broking",
      "posp",
      "register as posp",
      "life insurance",
      "health insurance",
      "car insurance",
      "two-wheeler insurance",
      "general insurance",
      "term insurance",
      "earn commission",
      "sell insurance",
      "insurance agent",
      "insurance training",
      "insurance certification",
      "claim support",
      "customer service",
      "digital insurance platform",
      "insurance products",
      "become a posp",
      "insurance benefits",
      "insurance eligibility",
      "insurance career",
      "insurance technology",
    ],

    href: URLS.FINSURE,
  },
  {
    name: "Become our POSP",
    keywords: [
      "posp",
      "point of sales person",
      "become posp",
      "insurance agent",
      "insurance partner",
      "earn with insurance",
      "join insurance",
      "insurance business",
      "ratnaafin posp",
      "posp registration",
      "digital insurance",
      "sell insurance",
      "insurance broking",
      "commission on insurance",
      "insurance entrepreneurship",
      "insurance reseller",
      "insurance seller program",
      "start insurance career",
      "insurance training",
    ],
    href: URLS.POSP,
  },
  {
    name: "Customer Login",
    keywords: [
      "Customer Login",
      "login",
      "sign in",
      "user id",
      "username",
      "password",
      "captcha",
      "secure access",
      "virtual keyboard",
      "authentication",
      "portal",
      "account access",
      "secure login",
      "customer portal",
      "secure access image",
      "secure access text",
      "forgot password",
      "reset password",
    ],
    href: URLS.CUSTOMERS,
  },
  {
    name: "RBI Sachet",
    keywords: [
      "RBI Sachet",
      "Reserve Bank",
      "Sachet portal",
      "illegal deposits",
      "complaints",
      "unauthorised deposit",
      "financial scam",
      "investor awareness",
      "SLCC",
      "regulator",
      "file complaint",
      "track complaint",
      "deposit schemes",
      "fraud",
      "cybercrime",
      "public awareness",
      "financial regulation",
      "complaint portal",
      "regulatory coordination",
      "complaint tracking",
    ],
    href: URLS.RBI_SACHET,
  },
  {
    name: "RBI CMS",
    keywords: [
      "RBI",
      "CMS",
      "Complaint Management System",
      "complaint",
      "grievance",
      "ombudsman",
      "file complaint",
      "track complaint",
      "appeal",
      "feedback",
      "RBI complaint portal",
      "online complaint",
      "bank complaint",
      "nbfc complaint",
      "digital grievance",
      "complaint tracking",
      "automated acknowledgement",
      "SMS acknowledgement",
      "IVR tracking",
      "Consumer Education and Protection",
      "Centralised Receipt and Processing Centre",
      "RBI Ombudsman",
      "integrated ombudsman",
      "customer grievance",
      "RBI CMS portal",
      "resolve complaints",
      "rbi.org.in cms",
      "cms.rbi.org.in",
      "regulatory complaints",
      "RBI regulated entity",
    ],
    href: `${URLS.RBI_CMS}#eng`,
  },
];

export const LoanSolutions = [
  {
    _id: 0,
    image: BusinessLoan,
    title: "Business Loan",
    key: "Business Loan",
    link: "Discover",
    href: ROUTES.product.businessLoan,
    value: "business_loan",
  },
  {
    _id: 1,
    image: HomeLoanImage,
    title: "Home Loan",
    key: "Home Loan",
    link: "Discover",
    href: ROUTES.product.homeLoan,
    value: "home_loan",
  },
  {
    _id: 2,
    image: MachineryLoan,
    title: "Micro Loan Against Property",
    key: "Micro LAP",
    link: "Discover",
    href: ROUTES.product.microlap,
    value: "micro_loan_against_property",
  },
  {
    _id: 3,
    image: MachineryEquipmentLoanImage,
    title: "Machinery Loan",
    key: "Machinery Loan",
    link: "Discover",
    href: ROUTES.product.machineryLoan,
    value: "machinery_loan",
  },
  {
    _id: 4,
    image: ResidentialSolarFinance,
    title: "Residential Solar Finance",
    key: "Residential Solar Finance",
    link: "Discover",
    href: ROUTES.product.residentialSolarLoan,
    value: "residential_solar_loan",
  },
  {
    _id: 5,
    image: CommercialSolarFinance,
    title: "Commercial/Industrial Solar Finance",
    key: "Commercial/Industrial Solar Finance",
    link: "Discover",
    href: ROUTES.product.commercialSolarLoan,
    value: "commercial_solar_loan",
  },
  {
    _id: 6,
    image: LoanAgainstProperty,
    title: "Loan Against Property",
    key: "Loan Against Property",
    link: "Discover",
    href: ROUTES.product.loanAgainstProperty,
    value: "loan_against_property",
  },
  {
    _id: 7,
    image: VendorFinance,
    title: "Vendor Finance",
    key: "Vendor Finance",
    link: "Discover",
    href: ROUTES.product.scfVendorFinance,
    value: "vendor_finance",
  },
  {
    _id: 8,
    image: DealerFinance,
    title: "Dealer Finance",
    key: "Dealer Finance",
    link: "Discover",
    href: ROUTES.product.scfDealerFinance,
    value: "dealer_finance",
  },
  {
    _id: 9,
    image: SaleInvoiceDiscounting,
    title: "Sale Invoice Discounting",
    key: "Sale Invoice Discounting",
    link: "Discover",
    href: ROUTES.product.scfSalesInvoiceDiscounting,
    value: "sale_invoice_discounting",
  },
  {
    _id: 10,
    image: PurchaseInvoiceDiscounting,
    title: "Purchase Invoice Discounting",
    key: "Purchase Invoice Discounting",
    link: "Discover",
    href: ROUTES.product.scfPurchaseInvoice,
    value: "purchase_invoice_discounting",
  },
  {
    _id: 11,
    image: WorkingCapitalLoanImage,
    title: "Working Capital Loan",
    key: "Working Capital Loan",
    link: "Discover",
    href: ROUTES.product.workingCapitalLoan,
    value: "working_capital_loan",
  },
  {
    _id: 12,
    image: RevenueBasedFunding,
    title: "Revenue Based Funding",
    key: "Revenue Based Funding",
    link: "Discover",
    href: ROUTES.product.revenuebasedfinance,
    value: "revenue_based_funding",
  },
];

export const MICRO_PAGES_META_DATA = {
  businessLoan: {
    overview: {
      title: "Apply for Instant Business Loan Online - Ratnaafin",
      description: "Get a business loan online in India. Instant loans for online businesses with quick approval, easy process and minimal docs.",
    },
    "interest-rates": {
      title: "Business Loan Interest Rates, Charges, Fees in India – Ratnaafin",
      description: "Get business loans at 14%*p.a. onwards. Easy online application, minimal documentation and fast approval.",
    },
    "eligibility-document": {
      title: "Business Loan Eligibility And Documents Required - Ratnaafin",
      description: "Learn about business loan eligibility criteria and documents required to apply. Simple process with clear requirements.",
    },
    "how-to-apply": {
      title: "Apply for Business Loan Online Upto ₹50 Lakh - Ratnaafin",
      description: "Apply for a business loan at 14% p.a. onwards. Get ₹3–50 lakh for 12–36 months with processing fees up to 2%.",
    },
    "emi-calculator": {
      title: "Business Loan EMI Calculator & Eligibility Tool - Ratnaafin",
      description: "Calculate business loan EMI and check eligibility using our online EMI calculator. Fast, accurate and easy to use.",
    },
  },
  machineryLoan: {
    overview: {
      title: "Machinery & Equipment Financing for MSME Businesses - Ratnaafin",
      description: "Get an MSME machinery loan for new or existing businesses. Collateral-free purchase with easy eligibility and quick approval.",
    },
    "interest-rates": {
      title: "Machinery Loan Interest Rate & Providers in India - Ratnaafin",
      description: "Check machinery loan interest rates for MSMEs in India. Get competitive rates, flexible tenure and quick approval.",
    },
    "eligibility-document": {
      title: "Machinery Loan Eligibility & Documents - Ratnaafin",
      description: "Check machinery loan eligibility criteria and documents required to apply. Simple process with clear requirements.",
    },
    "how-to-apply": {
      title: "How to Apply for Machinery Loan Online - Ratnaafin",
      description: "Learn how to apply for a machinery loan online. Simple steps, easy documentation and quick approval with Ratnaafin.",
    },
    "emi-calculator": {
      title: "Machinery Loan EMI Calculator Online - Ratnaafin",
      description: "Calculate machinery loan EMI online based on amount, tenure and interest rate. Plan repayments easily with Ratnaafin.",
    },
  },
};
